# lead_crm_library/salesforce/exceptions.py

class SalesforceError(Exception):
    pass
